feat: add network filter to pools page
TreasureProject/magicswapv2 pull request #70
Opened 2024-12-18 19:54 UTC by cdotta

<img width="867" alt="Screenshot 2024-12-18 at 4 51 24 PM" src="https://github.com/user-attachments/assets/633a09ec-d7ab-4743-a598-635efc2693d7" />

2024-12-19 17:57 UTC, alecananian requested changes
There should be an option to select "all" or "none" - basically, clear the filter so that the pools like shows items from all supported chains. This will also need to be refactored eventually because `ChainIcon` from ConnectKit doesn't support Treasure mainnet

2024-12-19 18:06 UTC, karelvuong commented on app/routes/pools.tsx
> +                    <span>Network:</span>
Minor but remove the `Network :` text and just replace it with depending on what's selected in the drop down:
- All Networks
- Treasure
- Arbitrum One
- etc.

<img width="270" alt="image" src="https://github.com/user-attachments/assets/dc089d1a-de76-4bf4-a553-ca350a89c976" />

2024-12-19 18:12 UTC, alecananian requested changes

2024-12-19 18:12 UTC, alecananian commented on app/routes/pools.tsx
> +                {selectedChain ? (
There's no way to clear `selectedChain` and return back to the "all" view

2024-12-19 18:12 UTC, alecananian commented on app/routes/pools.tsx
> +  const [selectedChain, setSelectedChain] = useState<Chain | null>(null);
Instead of `useState` this should be built in the same way as `handleSelectGame` using URL search params because this will require a new server-side refresh, and it enables us to have a deeplink to the chain view

2024-12-21 00:06 UTC, alecananian commented on app/routes/pools.tsx
> +                    <span>Network:</span>
Done. We can add an "All networks" icon if we have one to use

2024-12-21 00:07 UTC, merged